BEGIN;

CREATE TABLE IF NOT EXISTS rooms (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    votes_revealed boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS participants (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id uuid NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
    display_name text NOT NULL,
    vote text,
    joined_at timestamp with time zone NOT NULL DEFAULT now(),
    last_seen_at timestamp with time zone DEFAULT now(),
    UNIQUE (room_id, display_name)
);

COMMIT;
